name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    name: PHPCS
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run PHPCS
        run: composer phpcs
