name: Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPStan
        run: composer phpstan -- --error-format=github
